# Uses a AVRISP mkii instead of a serial programmer
# Use "make raw_upload" to upload to device

ARDUINO_DIR = /Applications/Arduino.app/Contents/Resources/Java

TARGET       			= SKETCH_NAME
MCU          			= atmega168
F_CPU        			= 16000000
AVRDUDE_ARD_PROGRAMMER 	= avrispmkii
ARD_PORT 				= usb

# Separate libraries with spaces
ARDUINO_LIBS = Servo LiquidCrystal EEPROM

include ./Arduino.mk
